import assert from 'node:assert/strict';
import { ArtifactScope, ProcessingQueue, withDeadline } from '../src/features/processingRuntime.ts';
const pause = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));
let release!: (value?: unknown) => void;
let active = 0;
let maximum = 0;
const queue = new ProcessingQueue(10);
const first = queue.run(async () => { maximum = Math.max(maximum, ++active); await new Promise(resolve => { release = resolve; }); active--; return 1; });
await assert.rejects(first, /timed out/);
await assert.rejects(queue.run(async () => { maximum = Math.max(maximum, ++active); active--; }), /unavailable/);
release();
await pause(0);
assert.equal(await queue.run(async () => 2), 2);
assert.equal(maximum, 1);
await assert.rejects(withDeadline(new Promise(() => {}), 5, 'stage'), /stage timed out/);
const files = new Set<string>();
const scope = new ArtifactScope(async uri => { files.delete(uri); });
let finish!: (value?: unknown) => void;
const late = scope.run(async () => {
  scope.track('late.jpg');
  await new Promise(resolve => { finish = resolve; });
  files.add('late.jpg');
});
await scope.close();
finish();
await late;
assert.equal(files.size, 0, 'late completed writes must be swept');
assert.throws(() => scope.assertOpen(), /cancelled/);
console.log('Processing regressions passed: bounded waits, no concurrent native calls, queue recovery, late artifact cleanup.');
